contents:
- name: 浮点数计算直线的斜率
  codes: slope.cpp
  code-pre: slope-pre.tex
- name: 分数精确计算直线的斜率
  codes: slope-frac.cpp
  code-pre: slope-frac-pre.tex
- name: 两点式转一般式
  codes: two-point-to-general.cpp
  code-pre: two-point-to-general-pre.tex
- name: 一般式转两点式
  codes: general-to-two-point.cpp
  code-pre: general-to-two-point-pre.tex
- name: 抛物线与 x 轴是否相交及交点
  codes: parabola-x-cross.cpp
  code-pre: parabola-x-cross-pre.tex
