contents:
- name: 三角形面积
  codes: triangle-area.cpp
- name: 三角形外心
  codes: circumcenter.cpp
  code-pre: circumcenter-pre.tex
- name: 三角形内心
  codes: incenter.cpp
  code-pre: incenter-pre.tex
- name: 三角形垂心
  codes: orthocenter.cpp
  code-pre: orthocenter-pre.tex
