contents:
- name: 三角形外接圆
  codes: circumscribed-circle.hpp
- name: 按圆心角取圆上点
  codes: get-point-on-circle.hpp
- name: 三角形内切圆
  codes: inscribed-circle.hpp
- name: 三角形垂心
  codes: orthocenter.hpp
- name: 点到圆最近点
  codes: point-to-circle.hpp
- name: 两圆公切线
  codes: tangent-cc.hpp
- name: 点-圆切线切点
  codes: tangent-cp.hpp
