contents:
- name: 库实数类实现（双精度）
  codes: double-real.cpp
- name: 平面几何必要初始化
  directory: plane-init
- name: 平面角度与弧度
  directory: angle-radian
- name: 平面点线相关
  directory: plane-point-line
- name: 平面圆相关（浮点数处理）
  directory: plane-circle
- name: 平面三角形相关（浮点数处理）
  directory: plane-triangle
- name: 平面直线方程转换
  directory: line-equation
- name: 平面多边形
  directory: plane-polygon
- name: 二维凸包
  directory: convex-hull-2d
- name: 三维几何必要初始化
  directory: 3d-init
- name: 三维点线面相关
  directory: 3d-point-line-plane
- name: 三维角度与弧度
  directory: 3d-angle-radian
- name: 空间多边形
  directory: 3d-polygon
