contents:
- name: 空间三点是否共线
  codes: 3d-on-line.cpp
  code-pre: 3d-on-line-pre.tex
- name: 四点是否共面
  codes: on-plane.cpp
- name: 空间点是否在线段上
  codes: 3d-point-on-segment.cpp
- name: 空间两点是否在线段同侧
  codes: 3d-point-segment-side.cpp
  code-pre: 3d-point-segment-side-pre.tex
- name: 两点是否在平面同侧
  codes: point-plane-side.cpp
  code-pre: point-plane-side-pre.tex
- name: 空间两直线是否平行/垂直
  codes: 3d-line-parallel.cpp
- name: 两平面是否平行/垂直
  codes: plane-parallel.cpp
- name: 空间两直线是否是同一条
  codes: 3d-same-line.cpp
- name: 两平面是否是同一个
  codes: same-plane.cpp
- name: 直线是否与平面平行
  codes: line-plane-parallel.cpp
- name: 空间两线段是否相交
  codes: 3d-segment-intersection.cpp
- name: 空间两直线是否相交及交点
  codes: 3d-line-intersection.cpp
  code-pre: 3d-line-intersection-pre.tex
- name: 直线与平面是否相交及交点
  codes: line-plane-cross.cpp
  code-pre: line-plane-cross-pre.tex
- name: 两平面是否相交及交线
  codes: plane-intersection.cpp
  code-pre: plane-intersection-pre.tex
- name: 点到直线的最近点与最近距离
  codes: 3d-point-to-line.cpp
- name: 点到平面的最近点与最近距离
  codes: point-to-plane.cpp
- name: 空间两直线的最近距离与最近点对
  codes: line-to-line.cpp
