contents:
  - name: 集合幂级数
    directory: 集合幂级数
  - name: 多项式
    directory: 多项式
  - name: 数论分块
    codes: 数论分块.cpp
    code-pre: 数论分块.tex
  - name: 狄利克雷卷积
    codes: 
    code-pre: 狄利克雷卷积.tex
  - name: 杜教筛
    code-pre: 杜教筛.tex
    codes: 杜教筛.cpp
    code-post: 杜教筛-post.tex
  - name: Powerful Number筛
    code-pre: PN-pre.tex
    codes: PN.cpp