contents:
  - name: 数论
    directory: 数论
  - name: 组合数学
    directory: 组合数学
  - name: 集合幂级数
    directory: 集合幂级数
  - name: 多项式
    directory: 多项式
  - name: 类欧几里得算法
    code-pre: 类欧.tex
    codes: 类欧.cpp
  - name: 本原毕达哥拉斯三元组
    code-pre: 本原毕达哥拉斯三元组.tex
    codes: 本原毕达哥拉斯三元组.cpp
  - name: 快速乘
    codes: 快速乘.cpp
  - name: 龟速乘
    codes: 龟速乘.cpp
  - name: Faray 数列
    code-pre: Faray-pre.tex
    codes: Faray.cpp
  - name: 亚线性 Faray 数列
    code-pre: Faray-master-pre.tex
    codes: Faray-master.cpp
