contents:
  - name: 数学
    directory: Math
  - name: 图论
    directory: Graph
  - name: 数据结构
    directory: DataStructure
  - name: qsort
    codes:
      - qsort.cpp
      - qsort.java
      - qsort.py