contents:
- name: 弧度角度相互转换
  codes: deg-arc.cpp
- name: 正弦定理
  code-pre: sine-rule-pre.tex
- name: 余弦定理（已知三角形三边，求角）
  codes: cosine-rule.cpp
  code-pre: cosine-rule-pre.tex
- name: 求两向量的夹角
  codes: vector-angle.cpp
  code-pre: vector-angle-pre.tex
- name: 向量旋转任意角度
  codes: rotate-any.cpp
  code-pre: rotate-any-pre.tex
- name: 点绕点旋转任意角度
  codes: rotate-point.cpp
  code-pre: rotate-point-pre.tex
