contents:
- name: 角度
  directory: angle
- name: 核心类型
  directory: class
- name: 求交点
  directory: cross-point
- name: 距离
  directory: distance
- name: 基础运算
  directory: operation
- name: 空间三角形
  directory: polygon
- name: 位置判定
  directory: position
- name: 体积
  directory: volume
